import React from 'react'

export default function oldicon() {
  return (
    <div>
      <Figure>

      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-properti.png"
      />
      <Figure.Caption>
        Properti
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-fashion.png"
      />
      <Figure.Caption>
        Fashion
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-fnb.png"
      />
      <Figure.Caption>
        Makanan & Minuman
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-kecantikan.png"
      />
      <Figure.Caption>
        Kecantikan
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-kesehatan.png"
      />
      <Figure.Caption>
        Kesehatan
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-umkm.png"
      />
      <Figure.Caption>
        UMKM
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-rumahtangga.png"
      />
      <Figure.Caption>
        Rumah Tangga
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-finance.png"
      />
      <Figure.Caption>
        Keuangan
      </Figure.Caption>
      <Figure.Image
        width={75}
        height={75}
        alt="171x180"
        src="/assets/icons/icon-jasa.png"
      />
      <Figure.Caption>
        Jasa
      </Figure.Caption>
      </Figure>

    </div>
  )
}
